### ISSUE TITLE
Ensure absent still requires "command"

### ISSUE THREAD

**Issue by bradq** [torrancew/puppet-cron#28]
Just happened to notice in some if(x) cron{} else cron{ensure=>absent} manifests that "command" is a requisite parameter even with ensure=>absent. Is this an intended approach? I don't spot anything in the schema that indicates that the command is being sanity checked, just a straight passthrough to file{}. 

Figured I'd check before a pull request because I'd prefer to not maintain a fork for such a trivial reason. If it's not intended let me know and I'll pass on a pull request. Thanks for this! I strictly adhere to having all non-stock cron tasks in cron.d for easy separation and perusal, but I've been stupid and forgotten a \n too many times to not use.

**Comment by felipe1982** [comment]
any progress on this?

**Comment by torrancew** [comment]
This will be released in v0.2.0, scheduled to hit the forge by the end of this week.
