### ISSUE TITLE
Under Archlinux, Package State Always Transitioning from Purged to Present

### ISSUE THREAD

**Issue by Nekroze** [torrancew/puppet-cron#30]
Hello,

Whenever I run puppet with your cron class included on arch linux it will set the install of cron from Purged to Present every time. This is not a problem as such, the module works. The problem i have with this is that i am reporting puppet runs to zabbix and it will forever come up with the alert that the puppet run made changes to the system.

I am guessing as this only seems to effect arch linux it will be pretty low priority but i am going to try and switch all my servers to centos soon anyways.

Thanks for your time and work on this module.

**Comment by torrancew** [comment]
@Nekroze  I believe you'll find better arch support in the upcoming 0.2.0 release -- sorry for the shoddy handling of this!

**Comment by Nekroze** [comment]
@torrancew All good mate. I moved away from puppet long ago now. Thanks for the responses all the same. Good luck with the new release.
