### ISSUE TITLE
install.pm fails on RedHat 5 

### ISSUE THREAD

**Issue by brgerig** [torrancew/puppet-cron#34]
On RedHat 5 systems, the package that supplies cron is vixie-cron, not cronie. Changing the code to the following fixes it, at least for all of the systems I've tested on:
```ruby
  $package_name = $operatingsystem ? {
    /(RedHat|CentOS|OracleLinux)/ => $lsbmajdistrelease ? {
        '5' => 'vixie-cron',
        default => 'cronie',
    },
    default => 'cron',
  }
```
I'm not sure how universal the lsbmajdistrelease fact is, though. It doesn't seem to be present on some Oracle Linux 6 systems, but it is on OL5.

**Comment by torrancew** [comment]
@brgerig AFAIK that fact is only available if you have the proper LSB-related packages installed. I'll see if we can find a more reliable fact to base this decision off of.

**Comment by brgerig** [comment]
Makes sense. I would imagine that operatingsystemrelease should be more reliable. I hadn't messed with regexes inside of conditional selectors before, but this change is working for me in the couple of test cases I've applied it to:
```
  $package_name = $operatingsystem ? {
    /(RedHat|CentOS|OracleLinux)/ => $operatingsystemrelease ? {
        /^5\./ => 'vixie-cron',
        default => 'cronie',
    },
    default  => 'cron',
  }
```

**Comment by torrancew** [comment]
Splendid, thanks! Will add this ASAP

**Comment by torrancew** [comment]
Sorry, didn't mean to close!

**Comment by brgerig** [comment]
Glad I could help. Thanks for getting this added!
