### ISSUE TITLE
service getting failed on puppet run

### ISSUE THREAD

**Issue by ashish1099** [torrancew/puppet-cron#38]
the puppet agent run fail, because the package is not installed and service resource is trying to restart it.
I have created a PR for this https://github.com/torrancew/puppet-cron/pull/36

```
Error: Could not start Service[crond]: Execution of '/sbin/service crond start' returned 1: crond: unrecognized service
Error: /Stage[main]/Profile::Base/Service[crond]/ensure: change from stopped to running failed: Could not start Service[crond]: Execution of '/sbin/service crond start' returned 1: crond: unrecognized service
```

**Comment by torrancew** [comment]
This was closed out independently (there were many requests for this) -- thank you!
