### ISSUE TITLE
Error on Puppet 4 - File mode must be string

### ISSUE THREAD

**Issue by bernardoVale** [torrancew/puppet-cron#41]
Error: Failed to apply catalog: Parameter mode failed on File[job_datapump]: The file mode specification must be a string, not 'Fixnum' at /etc/puppetlabs/code/environments/production/modules/cron/manifests/job.pp:48

I've could fixed it changing from:
      
     mode    => $mode
to:
      
     mode    => "$mode",

It appears to be related to this issue: https://tickets.puppetlabs.com/browse/PUP-2350

**Comment by roobert** [comment]
+1

**Comment by roman-mueller** [comment]
Already proposed as a PR, but this repo appears to be abandoned, see:
https://github.com/torrancew/puppet-cron/pull/32
